[package]
name = "nexum_cli"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "nexum"
path = "src/main.rs"

[dependencies]
nexum_core = { path = "../nexum_core" }
anyhow = { workspace = true }
tokio = { workspace = true }
